### ISSUE TITLE
No agents listed

### ISSUE THREAD

**Issue by ReplicaObscura** [ajf8/mcomaster#10]
I have my collective and all of my nodes listed in mcomaster, but none of my agents show up.

Is there anything special that needs to be done to ensure that the agents show up in mcomaster's interface? I can use them all from the command line with the 'mco' command and they work fine.

**Comment by esszopo** [comment]
Hi
I had the same issue, because I didn't copy mcollective/discovery/redisdiscovery.*

**Comment by ajf8** [comment]
I modified the logging for loading agent DDLs (which is likely where this is going wrong). Previously it threw all exceptions away, because some agents don't have DDLs and it would spam the console/logs. File permissions, gems not loading in the same ruby as mcomaster can be a problem.

Now it only throws the no DDL exception away, so maybe it will show up other problems in the console.

Or it could be a registration/discovery issue.

**Comment by lmello** [comment]
I i had this issue Of nodes and collectives being discovered but agents don't. This was because I was using mcollective 2.5.1 and the mcollective client gem on gem file was 2.2 and it was logging the error str_to_bool undefined method. I am prepared ng a pull request to change gemfile to solve this.

**Comment by lmello** [comment]
This new method was introduced on mcollective 2.4

**Comment by lmello** [comment]
@afj8 which versions of mcollective should we support, if I send the pull request it will support mcollective > 2.4 would that be OK ?

**Comment by ajf8** [comment]
@lmello Yeah I think it's probably about time to move to 2.4, that's fine. Thanks for preparing the pull request.

**Comment by lmello** [comment]
@bmcclure  could you check if this last commit fix your problem ?

**Comment by ReplicaObscura** [comment]
Sure, I won't be able to get back on this until next week but I will follow
up ASAP!

## 

Ben

**Comment by lmello** [comment]
@bmcclure  Thanks.

**Comment by lmello** [comment]
Hi we had fixed many problems , this problem should not exist anymore. 

Could you confirm that, so we could close this issue ? @bmcclure

You can test using vagrant, see VAGRANT.MD for help.
