### ISSUE TITLE
are this errors

### ISSUE THREAD

**Issue by esszopo** [ajf8/mcomaster#13]
:in app/assets/javascripts/helpers/mcclient.coffee
line 26:
is :if actionDdl.input[ddlKey]['optional']
should be if actionDdl.input[ddlKey]['optional']?
line 33:
is    validationRules[ddlKey]['minlength'] = actionDdl.input[ddlKey]['maxlength']
should be  validationRules[ddlKey]['minlength'] = actionDdl.input[ddlKey]['minlength']
line 40:
is validationRules[ddlKey]['dataType'] = "number"
should be validationRules[ddlKey]['remote']['dataType'] = "number"

**Comment by ajf8** [comment]
line 26: I didn't know about "?" in an if statement in coffeescript, nice. I think the validation plugin default is required=false, so it probably didn't cause a problem, but I like that this makes it more explicit. Otherwise, inverting the value is a bit pointless.

line 33 and 40: well spotted! fixed. :)

Thanks for the report.
