### ISSUE TITLE
MySQL?

### ISSUE THREAD

**Issue by tek0011** [ajf8/mcomaster#33]
Possible to use MySQL db?

**Comment by ajf8** [comment]
It should be, I think I did it a while ago, or maybe it was postgres.

Anyway - mcomaster uses rails activerecord. Since this supports mysql nicely, there shouldn't be a problem. Just look for general guidance on how to configure mysql with a rails app. Configure the database.yml, run the rake tasks to initialize the database, and add your users etc etc.
