### ISSUE TITLE
How to change refresh_interval?

### ISSUE THREAD

**Issue by stellatian** [ajf8/mcomaster#35]
I installed mcomaster. I noticed the /var/log/mcomaster/production.log is updated every 30 seconds:

Started GET "/nodes" for 123.45.67.89 at 2014-11-15 09:53:39 -0500
Processing by NodesController#index as JSON
 User Load (0.2ms)  SELECT  "users".\* FROM "users"  WHERE "users"."id" = 1  ORDER BY "users"."id" ASC LIMIT 1
Completed 200 OK in 2ms (Views: 0.1ms | ActiveRecord: 0.2ms)

I don't want it to check every 30 second and want to change it.
I checked /etc/mcomaster/application.yml and saw this:
# the hash below is sent to the client as JSON.

client:
  refresh_interval: 30 # how long between refreshes of agents, nodes, collectives?

I tried to increase refresh_interval to 300 (every 5 minutes), but it doesn't work. I made sure I restarted mcomaster after modification.

How to change it? Thanks!

**Comment by ajf8** [comment]
Hi there,

I've just tested changing this setting and it seems to work for me. I can see the client receives the setting, and also uses it when looking at the javascript for setting up the polling (in my browser debugger). This is in "development" mode rather than the RPM install, perhaps this is the difference...

If you view the HTML source, can you see a fragment like this? This should verify if the change you've made to the YAML is making it to the client.

```
    <script type="text/javascript">
        MCM.remoteConfig = {"refresh_interval":300,"action_shell":true};
```

**Comment by stellatian** [comment]
It seems working now!

<script type="text/javascript">
            MCM.remoteConfig = {"refresh_interval":300,"action_shell":true};

Thanks!

**Comment by ajf8** [comment]
Nice :+1:
